site_name: gli
theme:
  name: material
  palette:
    primary: black
    accent: teal
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
